
package logica;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PaqueteConMismoNombreException", targetNamespace = "http://logica/")
public class PaqueteConMismoNombreException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PaqueteConMismoNombreException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PaqueteConMismoNombreException_Exception(String message, PaqueteConMismoNombreException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PaqueteConMismoNombreException_Exception(String message, PaqueteConMismoNombreException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: logica.PaqueteConMismoNombreException
     */
    public PaqueteConMismoNombreException getFaultInfo() {
        return faultInfo;
    }

}
